import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "@/components/ui/ThemeToggle";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Set the page title and description.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is the main layout for the whole application.
export default function RootLayout({
  children,
}: Readonly<{
   // Children represents all pages inside this layout.
  children: React.ReactNode;
}>) {
  return (
    // Set the language and apply the fonts to the whole page
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       {/* The body contains everything shown on the page. */}
      <body className="min-h-full flex flex-col bg-gray-50 dark:bg-gray-900">
        {/* Display the header at the top of every page. */}
        <header className="border-b border-gray-200 bg-white px-8 py-3 dark:border-gray-700 dark:bg-gray-900">
          <div className="mx-auto flex max-w-5xl items-center justify-between">
             {/* Show the application name. */}
            <span className="text-lg font-semibold text-gray-900 dark:text-gray-100">
              CareerHub
            </span>
            {/* Display the light and dark mode toggle button. */}
            <ThemeToggle />
          </div>
        </header>
         {/* Wrap all pages with the TanStack Query provider. */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
